"""
test_diagram_regen.py — Agent-regen retry 邏輯單元測試

測試項目:
  1. get_available_azure_classes_summary() → 回傳格式化的 Azure 類別清單
  2. build_diagram_regen_prompt() → 正確建構 regen prompt
  3. _render_with_agent_regen() → 首次成功 / regen 後成功 / 全部重試失敗
"""

from __future__ import annotations

import json
import os
import shutil
import tempfile
from pathlib import Path
from typing import Any
from unittest.mock import AsyncMock, MagicMock, patch

import pytest

# 強制 mock mode
os.environ["MOCK_MODE"] = "true"
os.environ["RUN_MODE"] = "cli"

from orchestrator_app.contracts import (
    DiagramOutput,
    ResourceManifest,
    ResourceEntry,
    StepStatus,
)
from orchestrator_app.diagram_renderer import get_available_azure_classes_summary
from orchestrator_app.foundry_agents import build_diagram_regen_prompt, build_terraform_fix_prompt
from orchestrator_app.repair_feedback import (
    build_diagram_repair_payload,
    build_repair_context_json,
    build_terraform_repair_payload,
    render_prompt_block,
    render_repair_context_block,
)


# ======================================================================
# Fixtures
# ======================================================================
@pytest.fixture
def tmp_output_dir():
    d = tempfile.mkdtemp(prefix="regen_test_")
    yield Path(d)
    shutil.rmtree(d, ignore_errors=True)


@pytest.fixture
def sample_diag_output() -> DiagramOutput:
    """建立測試用 DiagramOutput（未渲染）。"""
    return DiagramOutput(
        diagram_py='from diagrams import Diagram\nwith Diagram("test"): pass',
        diagram_image=b"",
        render_log="",
        approved_resource_manifest=ResourceManifest(
            project_name="test",
            resources=[
                ResourceEntry(
                    resource_type="azurerm_resource_group",
                    name="rg",
                    display_name="Resource Group",
                )
            ],
        ),
        status=StepStatus.SUCCESS,
    )


def _make_success_render_result(code: str = "") -> DiagramOutput:
    """模擬渲染成功的 DiagramOutput。"""
    return DiagramOutput(
        diagram_py=code,
        diagram_image=b"\x89PNG_FAKE",
        diagram_image_ext="png",
        render_log="[Render] OK",
        status=StepStatus.SUCCESS,
    )


def _make_failed_render_result(code: str = "", error: str = "ImportError: cannot import name 'Foo'") -> DiagramOutput:
    """模擬渲染失敗的 DiagramOutput。"""
    return DiagramOutput(
        diagram_py=code,
        diagram_image=b"",
        render_log=f"[Render] FAILED: {error}",
        status=StepStatus.FAILED,
        error=error,
    )


def _make_regenerated_diag_output() -> DiagramOutput:
    """模擬 agent 重新產生的 DiagramOutput（已 parse）。"""
    return DiagramOutput(
        diagram_py='from diagrams import Diagram\nwith Diagram("regen"): pass',
        diagram_image=b"",
        render_log="regenerated by agent",
        approved_resource_manifest=ResourceManifest(),
        status=StepStatus.SUCCESS,
    )


def _make_mock_ctx() -> MagicMock:
    """建立模擬 WorkflowContext。"""
    ctx = MagicMock()
    ctx.get_state = MagicMock(side_effect=KeyError)
    ctx.yield_output = AsyncMock()
    return ctx


# ======================================================================
# Test: get_available_azure_classes_summary
# ======================================================================
class TestGetAvailableAzureClassesSummary:
    def test_returns_string(self):
        result = get_available_azure_classes_summary()
        assert isinstance(result, str)

    def test_contains_module_paths(self):
        """應包含 diagrams.azure.* 的模組路徑。"""
        result = get_available_azure_classes_summary()
        # diagrams 套件已安裝時，至少會有 compute / network 等模組
        if "diagrams package not installed" not in result:
            assert "diagrams.azure" in result
            # 至少包含幾行
            lines = [l for l in result.strip().split("\n") if l.strip()]
            assert len(lines) >= 3, f"Expected multiple module lines, got {len(lines)}"

    def test_format_colon_separated(self):
        """每行格式為 'module_path: Class1, Class2, ...'。"""
        result = get_available_azure_classes_summary()
        if "diagrams package not installed" not in result:
            for line in result.strip().split("\n"):
                if line.strip():
                    assert ": " in line, f"Line missing ': ' separator: {line}"


# ======================================================================
# Test: build_diagram_regen_prompt
# ======================================================================
class TestBuildDiagramRegenPrompt:
    def test_basic_structure(self):
        prompt = build_diagram_regen_prompt(
            spec_json='{"project_name": "test"}',
            architecture_details_json='{"details": "arch"}',
            previous_diagram_py='print("hello")',
            render_error="ImportError: cannot import name 'Foo'",
            available_classes_summary="diagrams.azure.compute: VM, AKS",
            previous_approved_resource_manifest_json='{"project_name":"test","resources":[]}',
            render_log="[Render] FAILED",
            regen_attempt=2,
        )
        assert isinstance(prompt, str)
        # 包含關鍵區段
        assert "渲染錯誤修正" in prompt
        assert "ImportError" in prompt
        assert 'print("hello")' in prompt
        assert "diagrams.azure.compute" in prompt
        assert "test" in prompt
        assert "render_log" in prompt
        assert "approved_resource_manifest" in prompt
        assert "第 2 次" in prompt or "Repair round: 2" in prompt

    def test_contains_json_instruction(self):
        """prompt 應指示回傳 JSON 格式。"""
        prompt = build_diagram_regen_prompt(
            spec_json="{}",
            architecture_details_json="{}",
            previous_diagram_py="",
            render_error="error",
            available_classes_summary="",
        )
        assert "JSON" in prompt
        assert "diagram_py" in prompt

    def test_includes_available_classes(self):
        classes_summary = "diagrams.azure.network: Firewall, VPN\ndiagrams.azure.compute: VM"
        prompt = build_diagram_regen_prompt(
            spec_json="{}",
            architecture_details_json="{}",
            previous_diagram_py="code",
            render_error="err",
            available_classes_summary=classes_summary,
        )
        assert "Firewall" in prompt
        assert "diagrams.azure.network" in prompt

    def test_includes_render_feedback_contract(self):
        repair_context_json = build_repair_context_json(
            repair_kind="diagram_regen",
            attempt=3,
            max_attempts=3,
            upstream_agent="Azure-Diagram-Generation-Agent",
            downstream_component="local diagram renderer",
            failure_message="err",
            execution_log="[Render] Attempt 1 failed",
            contract_name="approved_resource_manifest",
            contract_payload='{"resources":[]}',
            latest_artifact_name="diagram.py",
            latest_artifact_content="code",
        )
        prompt = build_diagram_regen_prompt(
            spec_json="{}",
            architecture_details_json="{}",
            previous_diagram_py="code",
            render_error="err",
            available_classes_summary="classes",
            previous_approved_resource_manifest_json='{"resources":[]}',
            render_log="[Render] Attempt 1 failed",
            regen_attempt=3,
            repair_context_json=repair_context_json,
        )
        assert "renderer" in prompt.lower() or "downstream" in prompt.lower()
        assert "[Render] Attempt 1 failed" in prompt
        assert '"resources":[]' in prompt
        assert "standardized repair context" in prompt.lower() or "標準化修復摘要" in prompt


class TestRepairContextHelper:
    def test_builds_structured_json_payload(self):
        payload = build_repair_context_json(
            repair_kind="terraform_validation_fix",
            attempt=1,
            max_attempts=2,
            upstream_agent="Azure-Terraform-Generation-Agent",
            downstream_component="terraform validate",
            failure_message="validate failed",
            execution_log="STDERR: boom",
            contract_name="approved_resource_manifest",
            contract_payload='{"project_name":"demo"}',
            latest_artifact_name="main.tf",
            latest_artifact_content="resource \"x\" \"y\" {}",
            preserved_invariants=["keep architecture unchanged"],
            extra_context={"variables_tf": "variable \"x\" {}"},
        )
        data = json.loads(payload)
        assert data["repair_kind"] == "terraform_validation_fix"
        assert data["contract"]["name"] == "approved_resource_manifest"
        assert data["contract"]["payload"]["project_name"] == "demo"
        assert data["latest_failed_artifact"]["name"] == "main.tf"
        assert data["extra_context"]["variables_tf"].startswith("variable")

    def test_terraform_fix_prompt_includes_repair_context(self):
        repair_context_json = build_repair_context_json(
            repair_kind="terraform_validation_fix",
            attempt=2,
            max_attempts=2,
            upstream_agent="Azure-Terraform-Generation-Agent",
            downstream_component="terraform init + validate",
            failure_message="terraform validate failed",
            execution_log="STDERR: invalid block",
            contract_name="approved_resource_manifest",
            contract_payload='{"project_name":"demo"}',
            latest_artifact_name="main.tf",
            latest_artifact_content="resource \"x\" \"y\" {}",
        )
        prompt = build_terraform_fix_prompt(
            spec_json='{"project_name":"demo"}',
            approved_resource_manifest_json='{"project_name":"demo"}',
            previous_main_tf='resource "x" "y" {}',
            previous_variables_tf='variable "name" {}',
            previous_outputs_tf='output "id" {}',
            validation_error="terraform validate failed",
            repair_context_json=repair_context_json,
        )
        assert "terraform validate failed" in prompt
        assert "machine-to-machine" in prompt.lower() or "標準化修復摘要" in prompt
        assert '"repair_kind": "terraform_validation_fix"' in prompt

    def test_render_repair_context_block_formats_markdown_section(self):
        payload = build_repair_context_json(
            repair_kind="diagram_regen",
            attempt=1,
            max_attempts=2,
            upstream_agent="Azure-Diagram-Generation-Agent",
            downstream_component="local diagram renderer",
            failure_message="boom",
        )
        block = render_repair_context_block(
            payload,
            heading="standardized repair context:",
        )
        assert block.startswith("standardized repair context:\n```json\n")
        assert '"repair_kind": "diagram_regen"' in block
        assert block.endswith("```\n\n")

    def test_render_prompt_block_formats_fenced_section(self):
        block = render_prompt_block("main.tf:", 'resource "x" "y" {}', language="hcl")
        assert block.startswith("main.tf:\n```hcl\n")
        assert 'resource "x" "y" {}' in block
        assert block.endswith("```\n\n")

    def test_build_terraform_repair_payload_renders_all_core_sections(self):
        payload = build_terraform_repair_payload(
            spec_json='{"project_name":"demo"}',
            approved_resource_manifest_json='{"project_name":"demo"}',
            previous_main_tf='resource "x" "y" {}',
            previous_variables_tf='variable "name" {}',
            previous_outputs_tf='output "id" {}',
            validation_error="terraform validate failed",
            previous_locals_tf='locals { x = 1 }',
            repair_context_json='{"repair_kind":"terraform_validation_fix"}',
            spec_heading="spec.json:",
            manifest_heading="approved_resource_manifest.json:",
            main_heading="main.tf:",
            variables_heading="variables.tf:",
            outputs_heading="outputs.tf:",
            locals_heading="locals.tf:",
            versions_heading="versions.tf:",
            providers_heading="providers.tf:",
            error_heading="terraform validation error:",
            repair_context_heading="standardized repair context:",
        )
        assert "spec.json:" in payload
        assert "main.tf:" in payload
        assert "locals.tf:" in payload
        assert "terraform validation error:" in payload
        assert "standardized repair context:" in payload

    def test_build_diagram_repair_payload_renders_all_core_sections(self):
        payload = build_diagram_repair_payload(
            spec_json='{"project_name":"demo"}',
            architecture_details_json='{"network":"private"}',
            previous_diagram_py='print("x")',
            render_error="ImportError",
            render_log="[Render] FAILED",
            previous_approved_resource_manifest_json='{"resources":[]}',
            available_classes_summary="diagrams.azure.compute: VM",
            repair_context_json='{"repair_kind":"diagram_regen"}',
            spec_heading="spec.json:",
            architecture_heading="architecture_details.json:",
            diagram_heading="latest failed diagram.py:",
            error_heading="render error:",
            render_log_heading="renderer render_log:",
            manifest_heading="manifest:",
            classes_heading="classes:",
            repair_context_heading="standardized repair context:",
        )
        assert "architecture_details.json:" in payload
        assert "latest failed diagram.py:" in payload
        assert "renderer render_log:" in payload
        assert "manifest:" in payload
        assert "classes:" in payload

    def test_rules_mentioned(self):
        """prompt 應提及只使用可用類別的規則。"""
        prompt = build_diagram_regen_prompt(
            spec_json="{}",
            architecture_details_json="{}",
            previous_diagram_py="",
            render_error="error",
            available_classes_summary="",
        )
        assert "可用類別" in prompt or "available" in prompt.lower()


# ======================================================================
# Test: mock_agents.build_diagram_regen_prompt
# ======================================================================
class TestMockBuildDiagramRegenPrompt:
    def test_mock_returns_string(self):
        from orchestrator_app.mock_agents import build_diagram_regen_prompt as mock_regen
        result = mock_regen(
            spec_json="{}",
            architecture_details_json="{}",
            previous_diagram_py="code",
            render_error="some error message",
            available_classes_summary="classes",
        )
        assert isinstance(result, str)
        assert "MOCK" in result
        assert "some error" in result


# ======================================================================
# Test: _render_with_agent_regen
# ======================================================================
class TestRenderWithAgentRegen:
    """測試 _render_with_agent_regen() 的三個主要情境。"""

    @pytest.mark.asyncio
    async def test_success_on_first_render(self, sample_diag_output, tmp_output_dir):
        """首次渲染成功 → 直接回傳，不呼叫 agent。"""
        mock_ctx = _make_mock_ctx()
        success_result = _make_success_render_result(sample_diag_output.diagram_py)

        with (
            patch(
                "orchestrator_app.diagram_renderer.render_diagram_locally",
                new_callable=AsyncMock,
                return_value=success_result,
            ) as mock_render,
            patch("orchestrator_app.executors.agents") as mock_agents_mod,
        ):
            from orchestrator_app.executors import _render_with_agent_regen

            result = await _render_with_agent_regen(
                sample_diag_output, tmp_output_dir, mock_ctx,
                spec_json='{"project_name": "test"}',
                arch_details_json="{}",
            )

        assert result.diagram_image == b"\x89PNG_FAKE"
        assert result.diagram_image_ext == "png"
        # Agent 不應被呼叫
        mock_agents_mod.invoke_agent_raw.assert_not_called()
        # render_diagram_locally 只呼叫一次
        mock_render.assert_awaited_once()

    @pytest.mark.asyncio
    async def test_success_after_one_regen(self, sample_diag_output, tmp_output_dir):
        """首次渲染失敗 → agent regen → 第二次渲染成功。"""
        mock_ctx = _make_mock_ctx()
        mock_ctx.get_state = MagicMock(side_effect=lambda key: "thread-existing" if key == "diag_response_id" else KeyError)
        failed_result = _make_failed_render_result(code='from diagrams import Diagram\nprint("autofixed")', error="ImportError: cannot import name 'Foo'")
        failed_result.render_log = "[Render] FAILED\n[AutoFix] changed import"
        success_result = _make_success_render_result()
        regen_output = _make_regenerated_diag_output()

        # render_diagram_locally: 第一次失敗，第二次成功
        render_side_effects = [failed_result, success_result]

        with (
            patch(
                "orchestrator_app.diagram_renderer.render_diagram_locally",
                new_callable=AsyncMock,
                side_effect=render_side_effects,
            ) as mock_render,
            patch("orchestrator_app.executors.agents") as mock_agents_mod,
            patch(
                "orchestrator_app.diagram_renderer.get_available_azure_classes_summary",
                return_value="diagrams.azure.compute: VM",
            ),
            patch("orchestrator_app.executors.write_diagram_output"),
        ):
            mock_agents_mod.invoke_agent_raw = AsyncMock(return_value=('{"diagram_py": "regen"}', "thread-1"))
            mock_agents_mod.parse_diagram_output.return_value = regen_output
            mock_agents_mod.build_diagram_regen_prompt.return_value = "regen prompt"

            from orchestrator_app.executors import _render_with_agent_regen

            result = await _render_with_agent_regen(
                sample_diag_output, tmp_output_dir, mock_ctx,
                spec_json='{"project_name": "test"}',
                arch_details_json="{}",
            )

        # 最終成功
        assert result.diagram_image == b"\x89PNG_FAKE"
        # Agent 被呼叫一次
        mock_agents_mod.invoke_agent_raw.assert_awaited_once()
        assert mock_agents_mod.invoke_agent_raw.await_args.kwargs["previous_response_id"] == "thread-existing"
        mock_agents_mod.build_diagram_regen_prompt.assert_called_once()
        regen_kwargs = mock_agents_mod.build_diagram_regen_prompt.call_args.kwargs
        assert regen_kwargs["previous_diagram_py"] == 'from diagrams import Diagram\nprint("autofixed")'
        assert regen_kwargs["render_log"] == "[Render] FAILED\n[AutoFix] changed import"
        manifest_payload = json.loads(regen_kwargs["previous_approved_resource_manifest_json"])
        assert manifest_payload["project_name"] == "test"
        mock_ctx.set_state.assert_any_call("diag_response_id", "thread-1")
        # render_diagram_locally 共被呼叫兩次（初次 + regen 後）
        assert mock_render.await_count == 2
        # 有向使用者輸出 regen 訊息
        assert any("regen" in str(c) for c in mock_ctx.yield_output.call_args_list)

    @pytest.mark.asyncio
    async def test_empty_regenerated_diagram_is_treated_as_failure(self, sample_diag_output, tmp_output_dir):
        """若 agent regen 回傳空 diagram.py，應視為 regen 失敗而非繼續渲染空檔。"""
        mock_ctx = _make_mock_ctx()
        failed_result = _make_failed_render_result(error="SyntaxError")
        empty_regen_output = DiagramOutput(
            diagram_py="",
            approved_resource_manifest=ResourceManifest(),
            status=StepStatus.SUCCESS,
        )

        with (
            patch(
                "orchestrator_app.diagram_renderer.render_diagram_locally",
                new_callable=AsyncMock,
                return_value=failed_result,
            ) as mock_render,
            patch("orchestrator_app.executors.agents") as mock_agents_mod,
            patch(
                "orchestrator_app.diagram_renderer.get_available_azure_classes_summary",
                return_value="diagrams.azure.compute: VM",
            ),
            patch("orchestrator_app.executors.MAX_AGENT_REGEN_RETRIES", 1),
        ):
            mock_agents_mod.invoke_agent_raw = AsyncMock(return_value=('{}', "thread-1"))
            mock_agents_mod.parse_diagram_output.return_value = empty_regen_output
            mock_agents_mod.build_diagram_regen_prompt.return_value = "regen prompt"

            from orchestrator_app.executors import _render_with_agent_regen

            result = await _render_with_agent_regen(
                sample_diag_output, tmp_output_dir, mock_ctx,
                spec_json='{"project_name": "test"}',
                arch_details_json="{}",
            )

        assert result.diagram_image == b""
        assert "empty diagram_py" in result.error
        mock_render.assert_awaited_once()

    @pytest.mark.asyncio
    async def test_all_retries_exhausted(self, sample_diag_output, tmp_output_dir):
        """渲染持續失敗 → 用完所有 regen 重試 → 回傳失敗。"""
        mock_ctx = _make_mock_ctx()
        failed_result = _make_failed_render_result(error="NameError: name 'BadClass' is not defined")
        regen_output = _make_regenerated_diag_output()

        with (
            patch(
                "orchestrator_app.diagram_renderer.render_diagram_locally",
                new_callable=AsyncMock,
                return_value=failed_result,  # 每次都失敗
            ) as mock_render,
            patch("orchestrator_app.executors.agents") as mock_agents_mod,
            patch(
                "orchestrator_app.diagram_renderer.get_available_azure_classes_summary",
                return_value="diagrams.azure.compute: VM",
            ),
            patch("orchestrator_app.executors.write_diagram_output"),
            patch("orchestrator_app.executors.MAX_AGENT_REGEN_RETRIES", 2),
        ):
            mock_agents_mod.invoke_agent_raw = AsyncMock(return_value=('{"diagram_py": "still bad"}', "thread-1"))
            mock_agents_mod.parse_diagram_output.return_value = regen_output
            mock_agents_mod.build_diagram_regen_prompt.return_value = "regen prompt"

            from orchestrator_app.executors import _render_with_agent_regen

            result = await _render_with_agent_regen(
                sample_diag_output, tmp_output_dir, mock_ctx,
                spec_json='{"project_name": "test"}',
                arch_details_json="{}",
            )

        # 最終失敗
        assert result.diagram_image == b""
        assert "exhausted" in result.error or "regen" in result.error.lower() or result.error
        # Agent 被呼叫 2 次（MAX_AGENT_REGEN_RETRIES=2）
        assert mock_agents_mod.invoke_agent_raw.await_count == 2
        # render 被呼叫 3 次（初次 + 2 次 regen 後）
        assert mock_render.await_count == 3

    @pytest.mark.asyncio
    async def test_agent_regen_call_fails(self, sample_diag_output, tmp_output_dir):
        """渲染失敗後 agent regen 呼叫本身失敗 → 停止重試。"""
        mock_ctx = _make_mock_ctx()
        failed_result = _make_failed_render_result(error="ImportError")

        with (
            patch(
                "orchestrator_app.diagram_renderer.render_diagram_locally",
                new_callable=AsyncMock,
                return_value=failed_result,
            ),
            patch("orchestrator_app.executors.agents") as mock_agents_mod,
            patch(
                "orchestrator_app.diagram_renderer.get_available_azure_classes_summary",
                return_value="diagrams.azure.compute: VM",
            ),
            patch("orchestrator_app.executors.MAX_AGENT_REGEN_RETRIES", 2),
        ):
            mock_agents_mod.build_diagram_regen_prompt.return_value = "regen prompt"
            mock_agents_mod.invoke_agent_raw = AsyncMock(side_effect=RuntimeError("Agent unreachable"))

            from orchestrator_app.executors import _render_with_agent_regen

            result = await _render_with_agent_regen(
                sample_diag_output, tmp_output_dir, mock_ctx,
                spec_json="{}",
                arch_details_json="{}",
            )

        # agent 失敗 → break → 回傳錯誤
        assert result.diagram_image == b"" or result.error
        assert "Agent regen failed" in result.error
        # 只嘗試呼叫一次 agent（第一次就出錯所以 break）
        mock_agents_mod.invoke_agent_raw.assert_awaited_once()

    @pytest.mark.asyncio
    async def test_preserves_resource_manifest(self, sample_diag_output, tmp_output_dir):
        """如果 agent regen 回傳空的 resource manifest，保留原本的。"""
        mock_ctx = _make_mock_ctx()
        failed_result = _make_failed_render_result()
        success_result = _make_success_render_result()

        # agent 回傳空的 manifest
        regen_output = DiagramOutput(
            diagram_py='from diagrams import Diagram\nwith Diagram("regen"): pass',
            approved_resource_manifest=ResourceManifest(),  # 空的
        )

        with (
            patch(
                "orchestrator_app.diagram_renderer.render_diagram_locally",
                new_callable=AsyncMock,
                side_effect=[failed_result, success_result],
            ),
            patch("orchestrator_app.executors.agents") as mock_agents_mod,
            patch(
                "orchestrator_app.diagram_renderer.get_available_azure_classes_summary",
                return_value="classes",
            ),
            patch("orchestrator_app.executors.write_diagram_output"),
        ):
            mock_agents_mod.invoke_agent_raw = AsyncMock(return_value=("{}", "t"))
            mock_agents_mod.parse_diagram_output.return_value = regen_output
            mock_agents_mod.build_diagram_regen_prompt.return_value = "prompt"

            from orchestrator_app.executors import _render_with_agent_regen

            original_manifest = sample_diag_output.approved_resource_manifest
            result = await _render_with_agent_regen(
                sample_diag_output, tmp_output_dir, mock_ctx,
                spec_json="{}",
                arch_details_json="{}",
            )

        # 原本的 manifest 被保留
        assert len(result.approved_resource_manifest.resources) == len(original_manifest.resources)
        assert result.approved_resource_manifest.project_name == original_manifest.project_name
