"""
mock_agents.py — Mock mode：不真的呼叫子 agent，回傳固定測試資料。

用途：
  - 離線開發 / CI 測試 / workflow 驗證
  - MOCK_MODE=true 時，main.py 會用此模組取代 foundry_agents.py 的呼叫

Public API（與 foundry_agents 保持一致）：
  invoke_agent_raw(agent_name, message, **) -> (str, str)
  classify_response(text, expected_schema) -> str
  build_terraform_prompt / build_diagram_prompt
  build_cost_structure_prompt / build_cost_browser_prompt
  parse_terraform_output / parse_diagram_output
  parse_cost_structure_output / parse_cost_output
  invoke_terraform_agent / invoke_diagram_agent
  invoke_cost_structure_agent / invoke_cost_browser_agent
"""

from __future__ import annotations

import base64
import json
import logging
import os

from .contracts import (
    CostLineItem,
    CostOutput,
    CostStructureOutput,
    DiagramOutput,
    ResourceEntry,
    ResourceManifest,
    StepStatus,
    TerraformOutput,
)

logger = logging.getLogger(__name__)

# Agent name constants (same as foundry_agents)
CLARIFICATION_AGENT = os.getenv("CLARIFICATION_AGENT_NAME", "Architecture-Clarification-Agent")
TERRAFORM_AGENT = os.getenv("TERRAFORM_AGENT_NAME", "Azure-Terraform-Architect-Agent")
DIAGRAM_AGENT = os.getenv("DIAGRAM_AGENT_NAME", "DaC-Dagrams-Mingrammer")
COST_AGENT = os.getenv("COST_AGENT_NAME", "Agent-AzureCalculator")
COST_BROWSER_AGENT = os.getenv("COST_BROWSER_AGENT_NAME", "Agent-AzureCalculator-BrowserAuto")

# ---------------------------------------------------------------------------
# Mock: Terraform Agent
# ---------------------------------------------------------------------------
MOCK_MAIN_TF = '''# ============================================================
# Auto-generated by Azure-Terraform-Architect-Agent (MOCK)
# ============================================================
terraform {
  required_version = ">= 1.5"
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">= 3.80"
    }
  }
}

provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "main" {
  name     = var.resource_group_name
  location = var.location
  tags     = var.tags
}

resource "azurerm_virtual_network" "main" {
  name                = "${var.project_name}-vnet"
  address_space       = ["10.0.0.0/16"]
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
  tags                = var.tags
}

resource "azurerm_subnet" "app" {
  name                 = "app-subnet"
  resource_group_name  = azurerm_resource_group.main.name
  virtual_network_name = azurerm_virtual_network.main.name
  address_prefixes     = ["10.0.1.0/24"]
}

resource "azurerm_app_service_plan" "main" {
  name                = "${var.project_name}-asp"
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
  sku {
    tier = "Standard"
    size = "S1"
  }
  tags = var.tags
}

resource "azurerm_app_service" "main" {
  name                = "${var.project_name}-app"
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
  app_service_plan_id = azurerm_app_service_plan.main.id
  tags                = var.tags
}
'''

MOCK_VARIABLES_TF = '''variable "project_name" {
  type    = string
  default = "mock-project"
}

variable "location" {
  type    = string
  default = "eastasia"
}

variable "resource_group_name" {
  type    = string
  default = "rg-mock-project"
}

variable "tags" {
  type = map(string)
  default = {
    environment = "dev"
    managed_by  = "terraform"
  }
}
'''

MOCK_OUTPUTS_TF = '''output "resource_group_id" {
  value = azurerm_resource_group.main.id
}

output "app_service_url" {
  value = azurerm_app_service.main.default_site_hostname
}
'''


def _mock_resource_manifest(project_name: str = "mock-project") -> ResourceManifest:
    """產生 mock resource manifest。"""
    return ResourceManifest(
        project_name=project_name,
        resources=[
            ResourceEntry(
                resource_type="azurerm_resource_group",
                name="main",
                display_name="Resource Group",
                sku="N/A",
                region="eastasia",
            ),
            ResourceEntry(
                resource_type="azurerm_virtual_network",
                name="main",
                display_name="Virtual Network",
                sku="N/A",
                region="eastasia",
                properties={"address_space": ["10.0.0.0/16"]},
            ),
            ResourceEntry(
                resource_type="azurerm_subnet",
                name="app",
                display_name="App Subnet",
                sku="N/A",
                region="eastasia",
            ),
            ResourceEntry(
                resource_type="azurerm_app_service_plan",
                name="main",
                display_name="App Service Plan",
                sku="Standard_S1",
                region="eastasia",
            ),
            ResourceEntry(
                resource_type="azurerm_app_service",
                name="main",
                display_name="App Service",
                sku="Standard_S1",
                region="eastasia",
            ),
        ],
        terraform_version=">=1.5",
        provider_version=">=3.80",
    )


async def invoke_terraform_agent(spec_json: str) -> TerraformOutput:
    """Mock: 回傳固定 Terraform 產物。"""
    logger.info("[Mock] invoke_terraform_agent called")
    spec_data = json.loads(spec_json)
    project_name = spec_data.get("project_name", "mock-project")
    return TerraformOutput(
        main_tf=MOCK_MAIN_TF,
        variables_tf=MOCK_VARIABLES_TF,
        outputs_tf=MOCK_OUTPUTS_TF,
        resource_manifest=_mock_resource_manifest(project_name),
        status=StepStatus.SUCCESS,
    )


# ---------------------------------------------------------------------------
# Mock: Diagram Agent
# ---------------------------------------------------------------------------
MOCK_DIAGRAM_PY = '''"""
Auto-generated diagram (MOCK) — uses mingrammer/diagrams library.
Run: python diagram.py
"""
from diagrams import Diagram, Cluster
from diagrams.azure.compute import AppServices
from diagrams.azure.network import VirtualNetworks, Subnets
from diagrams.azure.general import Resourcegroups

with Diagram("Mock Architecture", show=False, filename="diagram", outformat="png"):
    with Cluster("Resource Group"):
        vnet = VirtualNetworks("VNet")
        subnet = Subnets("App Subnet")
        app = AppServices("App Service")
        vnet >> subnet >> app
'''


async def invoke_diagram_agent(
    spec_json: str,
    resource_manifest_json: str,
) -> DiagramOutput:
    """Mock: 回傳固定 diagram 產物。"""
    logger.info("[Mock] invoke_diagram_agent called")
    return DiagramOutput(
        diagram_py=MOCK_DIAGRAM_PY,
        diagram_image=b"",  # 空 bytes — 由 Step 2b DiagramRendererAgent 本地渲染
        diagram_image_ext="png",
        render_log="[MOCK] Diagram code generated. Image will be rendered locally by DiagramRendererAgent (Step 2b).",
        approved_resource_manifest=_mock_resource_manifest("mock-project"),
        status=StepStatus.SUCCESS,
    )


# ---------------------------------------------------------------------------
# Mock: Cost Structure Agent (Step 3a)
# ---------------------------------------------------------------------------
async def invoke_cost_structure_agent(
    spec_json: str,
    resource_manifest_json: str,
) -> CostStructureOutput:
    """Mock: 回傳固定的成本結構。"""
    logger.info("[Mock] invoke_cost_structure_agent called")
    return CostStructureOutput(
        line_items=[
            CostLineItem(
                resource_type="azurerm_app_service_plan",
                name="main",
                display_name="App Service Plan",
                sku="Standard_S1",
                region="eastasia",
                product_id="DZH318Z0BWMS",
                meter="S1 App Service",
                unit="1 Hour",
                pricing_tier="Standard",
                quantity=730.0,
                estimated_monthly_usd=73.0,
                notes="Standard S1 plan",
            ),
            CostLineItem(
                resource_type="azurerm_virtual_network",
                name="main",
                display_name="Virtual Network",
                sku="N/A",
                region="eastasia",
                meter="VNet Peering",
                unit="GB",
                quantity=0.0,
                estimated_monthly_usd=0.0,
                notes="No cost for basic VNet",
            ),
            CostLineItem(
                resource_type="azurerm_subnet",
                name="app",
                display_name="App Subnet",
                sku="N/A",
                region="eastasia",
                estimated_monthly_usd=0.0,
                notes="No direct cost",
            ),
            CostLineItem(
                resource_type="azurerm_app_service",
                name="main",
                display_name="App Service",
                sku="Standard_S1",
                region="eastasia",
                product_id="DZH318Z0BWMS",
                meter="App Service",
                unit="1 Hour",
                pricing_tier="Standard",
                quantity=730.0,
                estimated_monthly_usd=0.0,
                notes="Included in App Service Plan",
            ),
            CostLineItem(
                resource_type="azurerm_resource_group",
                name="main",
                display_name="Resource Group",
                sku="N/A",
                region="eastasia",
                estimated_monthly_usd=0.0,
                notes="No cost for resource group",
            ),
        ],
        currency="USD",
        region="eastasia",
        total_estimated_monthly_usd=73.0,
        notes="Mock cost structure for testing",
        status=StepStatus.SUCCESS,
    )


# ---------------------------------------------------------------------------
# Mock: Cost Browser Agent (Step 3b)
# ---------------------------------------------------------------------------
async def invoke_cost_browser_agent(
    cost_structure_json: str,
) -> CostOutput:
    """Mock: 回傳固定 cost 產物（模擬 browser automation 結果）。"""
    logger.info("[Mock] invoke_cost_browser_agent called")
    return CostOutput(
        estimate_xlsx=b"",  # 空 bytes — mock 模式
        calculator_share_url="https://azure.com/e/mock-estimate-share-link-12345",
        monthly_estimate_usd=73.0,
        cost_breakdown=[
            {"resource": "App Service Plan (S1)", "sku": "Standard_S1", "monthly_usd": 73.0},
            {"resource": "Virtual Network", "sku": "N/A", "monthly_usd": 0.0},
        ],
        status=StepStatus.SUCCESS,
    )


# ---------------------------------------------------------------------------
# Multi-turn API (與 foundry_agents 保持一致)
# ---------------------------------------------------------------------------
_MOCK_ARCH_DETAILS_JSON = json.dumps({
    "architecture_details": {
        "core_services": ["App Service", "Virtual Network", "Subnet"],
        "data_layer": {"database": "none", "cache": "none"},
        "ingress": {"type": "App Service Direct", "waf_enabled": False},
        "security": {
            "key_vault": False,
            "hsm": False,
            "private_endpoints": False,
            "ddos_protection": False,
            "defender_for_cloud": False,
        },
        "identity": {"managed_identity": "system", "b2c": False},
        "network": {
            "topology": "standalone",
            "has_hub": False,
            "vpn_gateway": False,
            "expressroute": False,
        },
        "compliance": [],
        "availability": {"multi_region": False, "rto_minutes": 60, "rpo_minutes": 15},
        "monitoring": ["Application Insights"],
        "special_requirements": "[MOCK] Basic web app architecture",
        "confirmed_by_user": True,
    }
})


_MOCK_TERRAFORM_JSON = json.dumps({
    "main_tf": MOCK_MAIN_TF,
    "variables_tf": MOCK_VARIABLES_TF,
    "outputs_tf": MOCK_OUTPUTS_TF,
    "resource_manifest": {
        "project_name": "mock-project",
        "resources": [
            {"resource_type": "azurerm_resource_group", "name": "main",
             "display_name": "Resource Group", "sku": "N/A", "region": "eastasia"},
            {"resource_type": "azurerm_virtual_network", "name": "main",
             "display_name": "Virtual Network", "sku": "N/A", "region": "eastasia",
             "properties": {"address_space": ["10.0.0.0/16"]}},
            {"resource_type": "azurerm_subnet", "name": "app",
             "display_name": "App Subnet", "sku": "N/A", "region": "eastasia"},
            {"resource_type": "azurerm_app_service_plan", "name": "main",
             "display_name": "App Service Plan", "sku": "Standard_S1", "region": "eastasia"},
            {"resource_type": "azurerm_app_service", "name": "main",
             "display_name": "App Service", "sku": "Standard_S1", "region": "eastasia"},
        ],
        "terraform_version": ">=1.5",
        "provider_version": ">=3.80",
    },
})

_MOCK_DIAGRAM_JSON = json.dumps({
    "diagram_py": MOCK_DIAGRAM_PY,
    "render_log": "[MOCK] Diagram code generated.",
    "approved_resource_manifest": {
        "project_name": "mock-project",
        "resources": [
            {"resource_type": "azurerm_resource_group", "name": "main", "display_name": "Resource Group", "sku": "N/A", "region": "eastasia"},
            {"resource_type": "azurerm_virtual_network", "name": "main", "display_name": "Virtual Network", "sku": "N/A", "region": "eastasia"},
            {"resource_type": "azurerm_subnet", "name": "app", "display_name": "App Subnet", "sku": "N/A", "region": "eastasia"},
            {"resource_type": "azurerm_app_service_plan", "name": "main", "display_name": "App Service Plan", "sku": "Standard_S1", "region": "eastasia"},
            {"resource_type": "azurerm_app_service", "name": "main", "display_name": "App Service", "sku": "Standard_S1", "region": "eastasia"}
        ],
        "terraform_version": ">=1.5",
        "provider_version": ">=3.80"
    },
    "diagram_image_base64": "",
})

_MOCK_COST_STRUCTURE_JSON = json.dumps({
    "line_items": [
        {
            "resource_type": "azurerm_app_service_plan", "name": "main",
            "display_name": "App Service Plan", "sku": "Standard_S1",
            "region": "eastasia", "product_id": "DZH318Z0BWMS",
            "meter": "S1 App Service", "unit": "1 Hour",
            "pricing_tier": "Standard", "quantity": 730.0,
            "estimated_monthly_usd": 73.0, "notes": "Standard S1 plan",
        },
        {
            "resource_type": "azurerm_virtual_network", "name": "main",
            "display_name": "Virtual Network", "sku": "N/A",
            "region": "eastasia", "meter": "VNet Peering", "unit": "GB",
            "quantity": 0.0, "estimated_monthly_usd": 0.0,
            "notes": "No cost for basic VNet",
        },
    ],
    "currency": "USD",
    "region": "eastasia",
    "total_estimated_monthly_usd": 73.0,
    "notes": "Mock cost structure",
})

_MOCK_COST_JSON = json.dumps({
    "calculator_share_url": "https://azure.com/e/mock-estimate-share-link-12345",
    "estimate_xlsx_base64": "",
    "monthly_estimate_usd": 73.0,
    "cost_breakdown": [
        {"resource": "App Service Plan (S1)", "sku": "Standard_S1", "monthly_usd": 73.0},
        {"resource": "Virtual Network", "sku": "N/A", "monthly_usd": 0.0},
    ],
})


async def invoke_agent_raw(
    agent_name: str,
    message: str,
    *,
    previous_response_id: str | None = None,
    store: bool = True,
    retries: int = 2,
    delay: float = 5.0,
) -> tuple[str, str]:
    """Mock: 回傳固定 JSON string + 空 response_id。"""
    logger.info("[Mock] invoke_agent_raw agent=%s prev_id=%s", agent_name, previous_response_id)
    if agent_name == CLARIFICATION_AGENT:
        return _MOCK_ARCH_DETAILS_JSON, "mock-arch-clarification-rid-1"
    elif agent_name == TERRAFORM_AGENT:
        return _MOCK_TERRAFORM_JSON, "mock-terraform-rid-1"
    elif agent_name == DIAGRAM_AGENT:
        return _MOCK_DIAGRAM_JSON, "mock-diagram-rid-1"
    elif agent_name == COST_AGENT:
        return _MOCK_COST_STRUCTURE_JSON, "mock-cost-structure-rid-1"
    elif agent_name == COST_BROWSER_AGENT:
        return _MOCK_COST_JSON, "mock-cost-browser-rid-1"
    else:
        return json.dumps({"error": f"Unknown agent: {agent_name}"}), ""


def classify_response(text: str, expected_schema: type | None = None) -> str:
    """Mock: 永遠回傳 'final'（mock 不會追問）。"""
    return "final"


# Prompt builders (same interface as foundry_agents)
def build_architecture_clarification_prompt(spec_json: str) -> str:
    return f"[MOCK] Clarify architecture requirements for: {spec_json[:100]}"


def build_terraform_prompt(spec_json: str, approved_resource_manifest_json: str) -> str:
    return f"[MOCK] Generate Terraform for: {spec_json[:100]}"


def build_terraform_fix_prompt(
    spec_json: str,
    approved_resource_manifest_json: str,
    previous_main_tf: str,
    previous_variables_tf: str,
    previous_outputs_tf: str,
    validation_error: str,
    previous_locals_tf: str = "",
    previous_versions_tf: str = "",
    previous_providers_tf: str = "",
) -> str:
    return f"[MOCK] Fix Terraform after validation error: {validation_error[:200]}"


def build_diagram_prompt(spec_json: str, architecture_details_json: str = "{}") -> str:
    return f"[MOCK] Generate Diagram for: {spec_json[:100]}"


def build_diagram_regen_prompt(
    spec_json: str,
    architecture_details_json: str,
    previous_diagram_py: str,
    render_error: str,
    available_classes_summary: str,
) -> str:
    return f"[MOCK] Regen Diagram after error: {render_error[:100]}"


def build_cost_structure_prompt(spec_json: str, resource_manifest_json: str) -> str:
    return f"[MOCK] Convert architecture to cost structure: {spec_json[:100]}"


def build_cost_browser_prompt(cost_structure_json: str) -> str:
    return f"[MOCK] Browser automation with cost structure: {cost_structure_json[:100]}"


# Parse functions (same interface as foundry_agents)
def parse_terraform_output(raw_text: str) -> TerraformOutput:
    data = json.loads(raw_text)
    manifest_data = data.get("resource_manifest", {})
    if isinstance(manifest_data, str):
        manifest_data = json.loads(manifest_data)
    manifest = ResourceManifest(**manifest_data)
    return TerraformOutput(
        main_tf=data.get("main_tf", ""),
        variables_tf=data.get("variables_tf", ""),
        outputs_tf=data.get("outputs_tf", ""),
        locals_tf=data.get("locals_tf", ""),
        versions_tf=data.get("versions_tf", ""),
        providers_tf=data.get("providers_tf", ""),
        resource_manifest=manifest,
        status=StepStatus.SUCCESS,
    )


def parse_diagram_output(raw_text: str) -> DiagramOutput:
    data = json.loads(raw_text)
    image_b64 = data.get("diagram_image_base64", "")
    image_bytes = b""
    if image_b64:
        image_bytes = base64.b64decode(image_b64)
    manifest_data = data.get("approved_resource_manifest", {})
    if isinstance(manifest_data, str):
        manifest_data = json.loads(manifest_data)
    return DiagramOutput(
        diagram_py=data.get("diagram_py", ""),
        diagram_image=image_bytes,
        diagram_image_ext="png",
        render_log=data.get("render_log", ""),
        approved_resource_manifest=ResourceManifest(**manifest_data),
        status=StepStatus.SUCCESS,
    )


def parse_cost_structure_output(raw_text: str) -> CostStructureOutput:
    data = json.loads(raw_text)
    line_items = [CostLineItem(**item) for item in data.get("line_items", [])]
    return CostStructureOutput(
        line_items=line_items,
        currency=data.get("currency", "USD"),
        commitment=data.get("commitment", "PAYG"),
        region=data.get("region", ""),
        total_estimated_monthly_usd=data.get("total_estimated_monthly_usd", 0.0),
        notes=data.get("notes", ""),
        status=StepStatus.SUCCESS,
    )


def parse_cost_output(raw_text: str) -> CostOutput:
    data = json.loads(raw_text)
    xlsx_b64 = data.get("estimate_xlsx_base64", "")
    xlsx_bytes = b""
    if xlsx_b64:
        xlsx_bytes = base64.b64decode(xlsx_b64)
    return CostOutput(
        estimate_xlsx=xlsx_bytes,
        calculator_share_url=data.get("calculator_share_url", ""),
        monthly_estimate_usd=data.get("monthly_estimate_usd", 0.0),
        cost_breakdown=data.get("cost_breakdown", []),
        status=StepStatus.SUCCESS,
    )
